# Site settings
title: Solarwind OBS
subtitle: Zhongyang MA's Personal Home Page
url: "https://zhongyangma.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
timezone: Asia/Shanghai
description: >
  I'm Zhongyang Ma and this blog is concerned about web-related technologies. Most of the articles are my reading notes, covering a variety of topics in software development. Please feel free to leave a comment or contact me by email if you have any question.

# Your information
email: zhongyang.mzy@gmail.com
author: Zhongyang MA
avatar: "/img/avatar.png"
profile: Senior Java Developer, Open Source Enthusiast, PhD in Physics.
#twitter_username: twitter_username

profile_links:
  Email: "mailto:zhongyang.mzy@gmail.com"
  GitHub: "https://github.com/ZhongyangMA"
  LinkedIn: "https://www.linkedin.com/in/zhongyangma/?locale=en_US"

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: Zhongyang-Ma  # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    Articles: /articles/
    Category: /category/
    About: /about/

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 10
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
